import { StyleSheet } from 'react-native';
import { Colors } from '@/Theme/Variables';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    headerContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 18,
        paddingTop: 0,
        paddingBottom: 0,
    },
    iconsWrap: {
        flexDirection: 'row',
    },
    iconContainer: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 23,
    },
    bookmarkCartContainer: {
        flexDirection: 'row',
    },
    bookmarkWrap: {
        width: 65,
        height: 40,
        borderColor: 'black',
        borderWidth: 1,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    cartWrap: {
        width: 65,
        height: 40,
        backgroundColor: '#3C7363',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cartContainer: {
        flexDirection: 'row',
    },
    bookmarkText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'black',
        marginLeft: 6,
    },
    cartText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
        marginLeft: 4,
    },
    title: {
        fontSize: 25,
        fontWeight: 'bold',
        lineHeight: 30,
        marginBottom: 19,
        marginTop: 32,
    },
    dailyInspiationCard: {
        width: '100%',
        height: 560,
        // #3C736336
        borderRadius: 10,
        backgroundColor: 'white',
        elevation: 10,
        shadowColor: '#3C7363AA',
        shadowOffset: { width: -5, height: 8 },
        shadowOpacity: 100,
        shadowRadius: 10,
    },
    imageContainer: {
        width: '100%',
        height: 350,
        backgroundColor: 'gray',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
    },
    contentContainer: {
        width: '100%',
        height: 210,
        backgroundColor: '#3C736318',
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        padding: 10,
    },
    recipeName: {
        fontSize: 20,
        fontWeight: 'bold',
        marginTop: 10,
    },
    rateContainer: {
        flexDirection: 'row',
        gap: 3,
        marginTop: 5,
    },
    authorNameContainer: {
        flexDirection: 'row',
        marginTop: 16,
    },
    authorName: {
        color: '#3D7363',
        fontSize: 18,
        fontWeight: 'bold',
        marginLeft: 5,
    },
    addIngredientsBtn: {
        alignSelf: 'center',
        marginTop: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: 'black',
        borderWidth: 2,
        width: '70%',
        height: 40,
        borderRadius: 10,
        gap: 10,
    },
    addIngredientsText: {
        fontSize: 13,
        fontWeight: 'bold',
    },
    mealHeader: {
        padding: 18,
        paddingTop: 10,
        paddingBottom: 10,
    },
    mealHeaderIcon: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    mealHeaderTitle: {
        fontWeight: 'bold',
        fontSize: 16,
        color: Colors.GREENDARK,
    },
    mealSubHeader: {
        backgroundColor: '#B8D9D0',
    },
    mealSubHeaderTitle: {
        fontWeight: 'bold',
        color: Colors.GREENDARK,
        textAlign: 'center',
        paddingTop: 10,
    },
    mealSubHeaderDays: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        padding: 10,
        marginBottom: 10,
        marginTop: 5,
    },
    mealSubHeaderDayContainer: {
        backgroundColor: Colors.GREENDARK,
        padding: 4,
        borderRadius: 100,
        width: 40,
        height: 40,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    mealSubHeaderDay: {
        color: Colors.WHITE,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    mealSubHeaderButton1: {
        backgroundColor: Colors.GREENDARK,
        margin: 18,
        marginTop: 0,
        paddingTop: 10,
        paddingBottom: 10,
        borderRadius: 100,
    },
    mealSubHeaderButton1Text: {
        color: Colors.WHITE,
        fontWeight: 'bold',
        textAlign: 'center',
    },

    // Menu
    mealPlanningContainer: {
        paddingTop: 5,
        elevation: -1,
        zIndex: -1,
    },
    mealItemContainer: {
        elevation: -1,
    },
    mealItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 18,
        paddingBottom: 12,
        paddingTop: 12,
    },
    mealButton2: {
        backgroundColor: Colors.GREENDARK,
        borderRadius: 100,
        paddingLeft: 20,
        paddingRight: 20,
        // width: 100,
        // height: 40,
        position: 'relative',
    },
    mealButton2Text: {
        fontWeight: 'bold',
        color: Colors.WHITE,
    },
    mealText: {
        fontWeight: 'bold',
        color: Colors.GREENDARK,
    },
    mealMenu: {
        padding: 16,
        elevation: -1,
        zIndex: -1,
    },
    dishScroll: {
        overflow: 'scroll',
    },
    dishContainer: {
        width: 230,
        borderRadius: 16,
        backgroundColor: Colors.WHITE,
        shadowColor: 'black',
        shadowOpacity: 0.1,
        shadowOffset: { width: 15, height: 15 },
        shadowRadius: 10,
        marginBottom: 10,
        marginLeft: 5,
        marginRight: 5,
    },
    dishImageContainer: {
        position: 'relative',
    },
    dishImage: {
        width: 230,
        height: 150,
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
    },
    dishImageText: {
        position: 'absolute',
        bottom: 10,
        left: 10,
        color: Colors.WHITE,
        fontSize: 13,
        fontWeight: 'bold',
    },
    dishInformationContainer: {
        backgroundColor: Colors.WHITE,
        borderBottomLeftRadius: 16,
        borderBottomRightRadius: 16,
        paddingTop: 5,
        paddingBottom: 5,
        paddingLeft: 10,
    },
    dishInformationVotes: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    dishIconStar: {
        color: Colors.YELLOW,
        padding: 1,
        fontSize: 15,
    },
    dishName: {
        fontWeight: 'bold',
        color: Colors.GREENDARK,
        paddingBottom: 10,
    },
    mealDropdown: {
        // elevation: 6,
        // zIndex: 6,
    },
    mealDropdownMenu: {
        position: 'absolute',
        top: 40,
        right: 0,
        width: 215,
        backgroundColor: Colors.GRAY,
        borderRadius: 10,
        paddingTop: 2,
        paddingBottom: 2,
        shadowColor: 'black',
        shadowOpacity: 0.2,
        shadowOffset: { width: 1, height: -1 },
        // shadowRadius: 10,
        // elevation: -2,
        elevation: 1000,
        zIndex: 1000,
        flex: 1,
    },
    hide: {
        display: 'none',
    },
    mealDropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        paddingLeft: 10,
        paddingRight: 10,
        width: 215,
    },
    mealDropdownText: {
        paddingLeft: 7,
        fontWeight: 'bold',
        color: Colors.GREENDARK,
    },

    mealDropdownBtn: {
        backgroundColor: 'transparent',
        paddingLeft: 0,
        paddingRight: 0,
        paddingTop: 0,
        paddingBottom: 0,
        width: '100%',
    },
});
