import { StyleSheet } from 'react-native';
import { Colors } from '@/Theme/Variables';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    headerContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 18,
        paddingTop: 0,
        paddingBottom: 0,
    },
    iconsWrap: {
        flexDirection: 'row',
    },
    iconContainer: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 23,
    },
    bookmarkCartContainer: {
        flexDirection: 'row',
    },
    bookmarkWrap: {
        width: 65,
        height: 40,
        borderColor: 'black',
        borderWidth: 1,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    cartWrap: {
        width: 65,
        height: 40,
        backgroundColor: '#3C7363',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cartContainer: {
        flexDirection: 'row',
    },
    bookmarkText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'black',
        marginLeft: 6,
    },
    cartText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
        marginLeft: 4,
    },
    title: {
        fontSize: 25,
        fontWeight: 'bold',
        lineHeight: 30,
        marginBottom: 19,
        marginTop: 32,
    },
    dailyInspiationCard: {
        width: '100%',
        height: 560,
        // #3C736336
        borderRadius: 10,
        backgroundColor: 'white',
        elevation: 10,
        shadowColor: '#3C7363AA',
        shadowOffset: { width: -5, height: 8 },
        shadowOpacity: 100,
        shadowRadius: 10,
    },
    imageContainer: {
        width: '100%',
        height: 350,
        backgroundColor: 'gray',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
    },
    contentContainer: {
        width: '100%',
        height: 210,
        backgroundColor: '#3C736318',
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        padding: 10,
    },
    recipeName: {
        fontSize: 20,
        fontWeight: 'bold',
        marginTop: 10,
    },
    rateContainer: {
        flexDirection: 'row',
        gap: 3,
        marginTop: 5,
    },
    authorNameContainer: {
        flexDirection: 'row',
        marginTop: 16,
    },
    authorName: {
        color: '#3D7363',
        fontSize: 18,
        fontWeight: 'bold',
        marginLeft: 5,
    },
    addIngredientsBtn: {
        alignSelf: 'center',
        marginTop: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: 'black',
        borderWidth: 2,
        width: '70%',
        height: 40,
        borderRadius: 10,
        gap: 10,
    },
    addIngredientsText: {
        fontSize: 13,
        fontWeight: 'bold',
    },
    mealHeader: {
        padding: 18,
        paddingTop: 10,
        paddingBottom: 10,
    },
    mealHeaderIcon: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    mealHeaderTitle: {
        fontWeight: 'bold',
        fontSize: 16,
        color: Colors.GREENDARK,
    },
    mealSubHeader: {
        backgroundColor: '#B8D9D0',
    },
    mealSubHeaderTitle: {
        fontWeight: 'bold',
        color: Colors.GREENDARK,
        textAlign: 'center',
        paddingTop: 10,
    },
    mealSubHeaderDays: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        padding: 10,
        marginBottom: 10,
        marginTop: 5,
    },
    mealSubHeaderDay: {
        backgroundColor: Colors.GREENDARK,
        color: Colors.WHITE,
        padding: 4,
        borderRadius: 100,
        width: 30,
        height: 30,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    mealSubHeaderButton1: {
        backgroundColor: Colors.GREENDARK,
        color: Colors.WHITE,
        fontWeight: 'bold',
        textAlign: 'center',
        margin: 18,
        marginTop: 0,
        paddingTop: 7,
        paddingBottom: 7,
        borderRadius: 100,
    },
    // Menu
    mealMenu: {
        paddingTop: 5,
    },
    mealItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 18,
        paddingBottom: 12,
        paddingTop: 12,
    },
    mealButton2: {
        backgroundColor: Colors.GREENDARK,
        color: Colors.WHITE,
        borderRadius: 100,
        width: 100,
        height: 40,
        fontWeight: 'bold',
    },
    mealButtonText: {},
    mealText: {
        fontWeight: 'bold',
        color: Colors.GREENDARK,
    },
});
