export enum RootScreens {
    MAIN = 'Main',
    WELCOME = 'Welcome',
    LOGIN = 'Login',
    SIGNUP = 'Signup',
    SEARCH = 'Search',
    SEARCHBYINGREDIENTS = 'SearchByIngredients',
    ADDRECIPEFROMSEARCH = 'AddRecipeFromSearch',
    MEALPLANNING = 'MealPlanning',
    CREATERECIPES = 'CreateRecipeContainer',
    ONBOARDING = 'Onboarding',
    SETTINGS = 'Settings',
    ADDINGREDIENTS = 'AddIngredients',
    SEARCHRESULT = 'SearchResult',
    ENHANCESKILL = 'EnhanceSkill',
    ENHANCEDETAIL = 'EnhanceDetail',
}
