import { Colors } from '@/Theme/Variables';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        backgroundColor: Colors.WHITE,
        paddingLeft: 18,
        paddingRight: 18,
        minHeight: '100%',
    },
    py3: {
        paddingTop: 10,
        paddingBottom: 10,
    },
    subTitle: {
        color: Colors.GREENDARK,
        fontSize: 16,
    },
    choosesContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.GREENDARK,
        padding: 0,
        borderRadius: 100,
        marginTop: 10,
        width: 130,
    },
    choosesItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        // margin: 5,
        backgroundColor: 'transparent',
        borderRadius: 100,
        cursor: 'pointer',
    },
    choosesIcon: {
        paddingLeft: 5,
        paddingRight: 5,
        color: Colors.WHITE,
    },
    choosesTitle: {
        fontWeight: 'bold',
        color: Colors.WHITE,
    },
    choosesItemActive: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        margin: 5,
        borderRadius: 100,
        backgroundColor: Colors.WHITE,
        cursor: 'pointer',
    },
    choosesIconActive: {
        paddingLeft: 5,
        paddingRight: 5,
        color: Colors.GREENDARK,
    },
    choosesTitleActive: {
        color: Colors.GREENDARK,
        fontWeight: 'bold',
    },
    row: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        paddingTop: 10,
    },
    col5: {
        width: '50%',
        padding: 5,
    },
    dishContainer: {
        borderRadius: 16,
        // backgroundColor: Colors.GRAY,
        shadowColor: 'black',
        shadowOpacity: 0.5,
        shadowOffset: { width: 15, height: 15 },
        shadowRadius: 10,
        width: '100%',
        borderStyle: 'solid',
        borderWidth: 1,
        borderColor: Colors.GRAY,
    },
    dishImageContainer: {
        position: 'relative',
    },
    dishImage: {
        width: '100%',
        height: 100,
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
    },
    dishImageText: {
        position: 'absolute',
        bottom: 10,
        left: 10,
        color: Colors.WHITE,
        fontSize: 12,
        fontWeight: 'bold',
    },
    dishInformationContainer: {
        backgroundColor: Colors.WHITE,
        borderBottomLeftRadius: 16,
        borderBottomRightRadius: 16,
        paddingTop: 5,
        paddingBottom: 5,
        paddingLeft: 10,
        height: 80,
    },
    dishInformationContainer2: {
        backgroundColor: Colors.WHITE,
        borderBottomLeftRadius: 16,
        borderBottomRightRadius: 16,
        paddingTop: 5,
        paddingBottom: 5,
        height: 40,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dishInformationVotes: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 4,
        paddingBottom: 4,
    },
    dishIconStar: {
        color: Colors.YELLOW,
        paddingRight: 2,
        fontSize: 15,
    },
    dishName: {
        fontWeight: 'bold',
        color: Colors.GREENDARK,
        paddingBottom: 10,
        fontSize: 14,
    },
    dishName2: {
        fontWeight: 'bold',
        color: Colors.GREENDARK,
        fontSize: 14,
        textAlign: 'center',
    },
});
